/* Generated by inital Angular 4 creation. */
// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// Change IP for development (Running locally)

export const environment = {
  production: false,
  API_IP: 'http://localhost:3000/'
};
