/* Generated by inital Angular 4 creation. */
// Change Rails backend IP for production (Running on VM)
export const environment = {
  production: true,
  API_IP: 'http://csc415-server23.hpc.tcnj.edu:3000/'
};
